apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
    color: blue  # Initially route traffic to blue deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

